module.exports = app => {
   app.route('/administrador')
      .get(app.api.administrador.get)  
      .get(app.api.administrador.getu) 
      .delete(app.api.administrador.del) 
      .post(app.api.administrador.add)
      .put(app.api.administrador.att)

   app.route('/antropometria')
      .get(app.api.antropometria.get)  
      .get(app.api.antropometria.getu) 
      .delete(app.api.antropometria.del) 
      .post(app.api.antropometria.add)
      .put(app.api.antropometria.att)

      app.route('/avaliacao')
      .get(app.api.avaliacao.get)  
      .get(app.api.avaliacao.getu) 
      .delete(app.api.avaliacao.del) 
      .post(app.api.avaliacao.add)
      .put(app.api.avaliacao.att)
    
   app.route('/avaliacaoglobal')
      .get(app.api.avaliacaoglobal.get)  
      .get(app.api.avaliacaoglobal.getu) 
      .delete(app.api.avaliacaoglobal.del) 
      .post(app.api.avaliacaoglobal.add)
      .put(app.api.avaliacaoglobal.att)

   app.route('/nutricionista')
      .get(app.api.nutricionista.get)  
      .get(app.api.nutricionista.getu) 
      .delete(app.api.nutricionista.del) 
      .post(app.api.nutricionista.add)
      .put(app.api.nutricionista.att)

   app.route('/paciente')
      .get(app.api.paciente.get)  
      .get(app.api.paciente.getu) 
      .delete(app.api.paciente.del) 
      .post(app.api.paciente.add)
      .put(app.api.paciente.att)

   app.route('/versaomedico')
      .get(app.api.versaomedico.get)  
      .get(app.api.versaomedico.getu) 
      .delete(app.api.versaomedico.del) 
      .post(app.api.versaomedico.add)
      .put(app.api.versaomedico.att)

   app.route('/versaopaciente')
      .get(app.api.versaopaciente.get)  
      .get(app.api.versaopaciente.getu) 
      .delete(app.api.versaopaciente.del) 
      .post(app.api.versaopaciente.add)
      .put(app.api.versaopaciente.att)

   app.route('/sintomas')
      .get(app.api.sintomas.get)  
      .get(app.api.sintomas.getu) 
      .delete(app.api.sintomas.del) 
      .post(app.api.sintomas.add)
      .put(app.api.sintomas.att)

   app.route('/exameFisico')
      .get(app.api.exameFisico.get)  
      .get(app.api.exameFisico.getu) 
      .delete(app.api.exameFisico.del) 
      .post(app.api.exameFisico.add)
      .put(app.api.exameFisico.att)

   app.route('/concicaoClinica')
      .get(app.api.concicaoClinica.get)  
      .get(app.api.concicaoClinica.getu) 
      .delete(app.api.concicaoClinica.del) 
      .post(app.api.concicaoClinica.add)
      .put(app.api.concicaoClinica.att)

   app.route('/EfisVmed')
      .get(app.api.EfisVmed.get)  
      .get(app.api.EfisVmed.getu) 
      .delete(app.api.EfisVmed.del) 
      .post(app.api.EfisVmed.add)
      .put(app.api.EfisVmed.att)

   app.route('/CcliVmed')
      .get(app.api.CcliVmed.get)  
      .get(app.api.CcliVmed.getu) 
      .delete(app.api.CcliVmed.del) 
      .post(app.api.CcliVmed.add)
      .put(app.api.CcliVmed.att)

   app.route('/SinVpac')
      .get(app.api.SinVpac.get)  
      .get(app.api.SinVpac.getu) 
      .delete(app.api.SinVpac.del) 
      .post(app.api.SinVpac.add)
      .put(app.api.SinVpac.att)
}