module.exports = app => {
   app.route('/administrador')
      .get(app.api.administrador.get)  
      .get(app.api.administrador.getu) 
      .delete(app.api.administrador.del) 
      .post(app.api.administrador.add)
      .put(app.api.administrador.att)

   app.route('/antropometria')
      .get(app.api.antropometria.get)  
      .get(app.api.antropometria.getu) 
      .delete(app.api.antropometria.del) 
      .post(app.api.antropometria.add)
      .put(app.api.antropometria.att)

      app.route('/avaliacao')
      .get(app.api.avaliacao.get)  
      .get(app.api.avaliacao.getu) 
      .delete(app.api.avaliacao.del) 
      .post(app.api.avaliacao.add)
      .put(app.api.avaliacao.att)
    
   app.route('/avaliacaoglobal')
      .get(app.api.avaliacaoglobal.get)  
      .get(app.api.avaliacaoglobal.getu) 
      .delete(app.api.avaliacaoglobal.del) 
      .post(app.api.avaliacaoglobal.add)
      .put(app.api.avaliacaoglobal.att)

   app.route('/nutricionista')
      .get(app.api.nutricionista.get)  
      .get(app.api.nutricionista.getu) 
      .delete(app.api.nutricionista.del) 
      .post(app.api.nutricionista.add)
      .put(app.api.nutricionista.att)

   app.route('/paciente')
      .get(app.api.paciente.get)  
      .get(app.api.paciente.getu) 
      .delete(app.api.paciente.del) 
      .post(app.api.paciente.add)
      .put(app.api.paciente.att)

   app.route('/versaomedico')
      .get(app.api.versaomedico.get)  
      .get(app.api.versaomedico.getu) 
      .delete(app.api.versaomedico.del) 
      .post(app.api.versaomedico.add)
      .put(app.api.versaomedico.att)

   app.route('/versaopaciente')
      .get(app.api.versaopaciente.get)  
      .get(app.api.versaopaciente.getu) 
      .delete(app.api.versaopaciente.del) 
      .post(app.api.versaopaciente.add)
      .put(app.api.versaopaciente.att)

   app.route('/sintomas')
      .get(app.api.sintomas.get)  
      .get(app.api.sintomas.getu) 
      .delete(app.api.sintomas.del) 
      .post(app.api.sintomas.add)
      .put(app.api.sintomas.att)

   app.route('/examefisico')
      .get(app.api.examefisico.get)  
      .get(app.api.examefisico.getu) 
      .delete(app.api.examefisico.del) 
      .post(app.api.examefisico.add)
      .put(app.api.examefisico.att)

   app.route('/condicaoclinica')
      .get(app.api.condicaoclinica.get)  
      .get(app.api.condicaoclinica.getu) 
      .delete(app.api.condicaoclinica.del) 
      .post(app.api.condicaoclinica.add)
      .put(app.api.condicaoclinica.att)

   app.route('/efisemad')
      .get(app.api.efisemad.get)  
      .get(app.api.efisemad.getu) 
      .delete(app.api.efisemad.del) 
      .post(app.api.efisemad.add)
      .put(app.api.efisemad.att)

   app.route('/cclivmed')
      .get(app.api.cclivmed.get)  
      .get(app.api.cclivmed.getu) 
      .delete(app.api.cclivmed.del) 
      .post(app.api.cclivmed.add)
      .put(app.api.cclivmed.att)

   app.route('/sinvpac')
      .get(app.api.sinvpac.get)  
      .get(app.api.sinvpac.getu) 
      .delete(app.api.sinvpac.del) 
      .post(app.api.sinvpac.add)
      .put(app.api.sinvpac.att)
}